// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (token_hash, user_id, expires_at, ip, user_agent)
VALUES ($1, $2, now() + interval '30 days', $3, $4)
RETURNING expires_at
`

type CreateSessionParams struct {
	TokenHash []byte      `json:"token_hash"`
	UserID    uuid.UUID   `json:"user_id"`
	Ip        *netip.Addr `json:"ip"`
	UserAgent *string     `json:"user_agent"`
}

// Session lifecycle. The session TTL (30-day idle expiry, docs/ARCHITECTURE.md
// -> Auth & sessions) lives in this file: both INSERT and touch use the same
// interval literal.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
	)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const deleteAllSessionsForUser = `-- name: DeleteAllSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteAllSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsForUser, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT s.last_seen_at, u.id, u.email, u.email_verified_at, u.password_hash, u.display_name, u.locale, u.country, u.role, u.stripe_account_id, u.stripe_customer_id, u.anonymized_at, u.created_at, u.updated_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetSessionWithUserRow struct {
	LastSeenAt       time.Time  `json:"last_seen_at"`
	ID               uuid.UUID  `json:"id"`
	Email            string     `json:"email"`
	EmailVerifiedAt  *time.Time `json:"email_verified_at"`
	PasswordHash     string     `json:"password_hash"`
	DisplayName      string     `json:"display_name"`
	Locale           string     `json:"locale"`
	Country          *string    `json:"country"`
	Role             string     `json:"role"`
	StripeAccountID  *string    `json:"stripe_account_id"`
	StripeCustomerID *string    `json:"stripe_customer_id"`
	AnonymizedAt     *time.Time `json:"anonymized_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, tokenHash []byte) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, tokenHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.LastSeenAt,
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.Country,
		&i.Role,
		&i.StripeAccountID,
		&i.StripeCustomerID,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now(), expires_at = now() + interval '30 days'
WHERE token_hash = $1
`

func (q *Queries) TouchSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, touchSession, tokenHash)
	return err
}
