// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (token_hash, user_id, expires_at, ip, user_agent)
VALUES ($1, $2, now() + interval '30 days', $3, $4)
RETURNING expires_at
`

type CreateSessionParams struct {
	TokenHash []byte      `json:"token_hash"`
	UserID    uuid.UUID   `json:"user_id"`
	Ip        *netip.Addr `json:"ip"`
	UserAgent *string     `json:"user_agent"`
}

// Session lifecycle. The session TTL (30-day idle expiry, docs/ARCHITECTURE.md
// -> Auth & sessions) lives in this file: both INSERT and touch use the same
// interval literal.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
	)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const deleteAllSessionsForUser = `-- name: DeleteAllSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteAllSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsForUser, userID)
	return err
}

const deleteExpiredSessionsBatch = `-- name: DeleteExpiredSessionsBatch :execrows
DELETE FROM sessions
WHERE token_hash IN (
    SELECT s.token_hash FROM sessions s
    WHERE s.expires_at < $1
    LIMIT $2
)
`

type DeleteExpiredSessionsBatchParams struct {
	Cutoff    time.Time `json:"cutoff"`
	BatchSize int32     `json:"batch_size"`
}

// Janitor batch (#142): sessions are kept until expiry + 30 days
// (docs/DATA_MODEL.md retention table) - reads already filter on expires_at,
// so this is row bookkeeping, not correctness. Selecting the batch by primary
// key bounds each DELETE's lock hold like the other jobs' batches (#99).
func (q *Queries) DeleteExpiredSessionsBatch(ctx context.Context, arg DeleteExpiredSessionsBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessionsBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUserExcept = `-- name: DeleteSessionsForUserExcept :exec
DELETE FROM sessions WHERE user_id = $1 AND token_hash <> $2
`

type DeleteSessionsForUserExceptParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
}

func (q *Queries) DeleteSessionsForUserExcept(ctx context.Context, arg DeleteSessionsForUserExceptParams) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUserExcept, arg.UserID, arg.TokenHash)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT s.last_seen_at, u.id, u.email, u.email_verified_at, u.password_hash, u.display_name, u.locale, u.country, u.created_at, u.updated_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetSessionWithUserRow struct {
	LastSeenAt      time.Time  `json:"last_seen_at"`
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	Locale          string     `json:"locale"`
	Country         *string    `json:"country"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, tokenHash []byte) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, tokenHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.LastSeenAt,
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now(), expires_at = now() + interval '30 days'
WHERE token_hash = $1
`

func (q *Queries) TouchSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, touchSession, tokenHash)
	return err
}
