// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPolicyAck = `-- name: CreatePolicyAck :exec
INSERT INTO policy_acks (id, user_id, race_id, policy)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, race_id) DO NOTHING
`

type CreatePolicyAckParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	RaceID uuid.UUID `json:"race_id"`
	Policy string    `json:"policy"`
}

// Idempotent: one ack per (user, race). Re-acking is a no-op, not an error.
func (q *Queries) CreatePolicyAck(ctx context.Context, arg CreatePolicyAckParams) error {
	_, err := q.db.Exec(ctx, createPolicyAck,
		arg.ID,
		arg.UserID,
		arg.RaceID,
		arg.Policy,
	)
	return err
}

const createThread = `-- name: CreateThread :one
WITH created AS (
    INSERT INTO chat_threads (id, listing_id, buyer_id)
    SELECT $1, $2, $3
    WHERE EXISTS (SELECT 1 FROM listings WHERE id = $2 AND status = 'active')
    ON CONFLICT (listing_id, buyer_id) DO NOTHING
    RETURNING id, listing_id, buyer_id, created_at, last_message_at, buyer_last_read_at, seller_last_read_at
)
SELECT id, listing_id, buyer_id, created_at, last_message_at, buyer_last_read_at, seller_last_read_at
FROM created
UNION ALL
SELECT id, listing_id, buyer_id, created_at, last_message_at, buyer_last_read_at, seller_last_read_at
FROM chat_threads
WHERE listing_id = $2 AND buyer_id = $3
LIMIT 1
`

type CreateThreadParams struct {
	ID        uuid.UUID `json:"id"`
	ListingID uuid.UUID `json:"listing_id"`
	BuyerID   uuid.UUID `json:"buyer_id"`
}

type CreateThreadRow struct {
	ID               uuid.UUID  `json:"id"`
	ListingID        uuid.UUID  `json:"listing_id"`
	BuyerID          uuid.UUID  `json:"buyer_id"`
	CreatedAt        time.Time  `json:"created_at"`
	LastMessageAt    *time.Time `json:"last_message_at"`
	BuyerLastReadAt  *time.Time `json:"buyer_last_read_at"`
	SellerLastReadAt *time.Time `json:"seller_last_read_at"`
}

// Find-or-create the (listing, buyer) thread, creating only while the listing is
// still active at write time. This closes the TOCTOU between the handler's
// active-check and this insert; ON CONFLICT DO NOTHING avoids writing a dead row
// when the thread already exists (no MVCC churn on re-contact). The row comes
// back with its real last_message_at - NULL only for a brand-new thread, which
// is how the first message is detected. Zero rows means "no thread yet and the
// listing is not active", which the handler maps to 409.
func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (CreateThreadRow, error) {
	row := q.db.QueryRow(ctx, createThread, arg.ID, arg.ListingID, arg.BuyerID)
	var i CreateThreadRow
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.BuyerLastReadAt,
		&i.SellerLastReadAt,
	)
	return i, err
}

const deleteExpiredMessagesByID = `-- name: DeleteExpiredMessagesByID :execrows
DELETE FROM messages WHERE id = ANY($1::uuid[])
`

// Deletes exactly the batch ListExpiredMessageBatch returned - see its
// comment. Returns the number deleted.
func (q *Queries) DeleteExpiredMessagesByID(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMessagesByID, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMessageImage = `-- name: GetMessageImage :one
SELECT m.image_key, t.buyer_id, l.seller_id
FROM messages m
JOIN chat_threads t ON t.id = m.thread_id
JOIN listings l ON l.id = t.listing_id
WHERE m.id = $1 AND m.thread_id = $2
`

type GetMessageImageParams struct {
	ID       uuid.UUID `json:"id"`
	ThreadID uuid.UUID `json:"thread_id"`
}

type GetMessageImageRow struct {
	ImageKey *string   `json:"image_key"`
	BuyerID  uuid.UUID `json:"buyer_id"`
	SellerID uuid.UUID `json:"seller_id"`
}

// A message's image plus the thread participants, for the authorized download.
// Scoped by thread_id (from the URL) so a message id from another thread cannot
// be fetched through this thread's route.
func (q *Queries) GetMessageImage(ctx context.Context, arg GetMessageImageParams) (GetMessageImageRow, error) {
	row := q.db.QueryRow(ctx, getMessageImage, arg.ID, arg.ThreadID)
	var i GetMessageImageRow
	err := row.Scan(&i.ImageKey, &i.BuyerID, &i.SellerID)
	return i, err
}

const getPolicyAck = `-- name: GetPolicyAck :one
SELECT id, user_id, race_id, policy, acked_at FROM policy_acks WHERE user_id = $1 AND race_id = $2
`

type GetPolicyAckParams struct {
	UserID uuid.UUID `json:"user_id"`
	RaceID uuid.UUID `json:"race_id"`
}

func (q *Queries) GetPolicyAck(ctx context.Context, arg GetPolicyAckParams) (PolicyAck, error) {
	row := q.db.QueryRow(ctx, getPolicyAck, arg.UserID, arg.RaceID)
	var i PolicyAck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RaceID,
		&i.Policy,
		&i.AckedAt,
	)
	return i, err
}

const getThreadParticipants = `-- name: GetThreadParticipants :one
SELECT t.id, t.buyer_id, t.last_message_at, l.seller_id
FROM chat_threads t
JOIN listings l ON l.id = t.listing_id
WHERE t.id = $1
`

type GetThreadParticipantsRow struct {
	ID            uuid.UUID  `json:"id"`
	BuyerID       uuid.UUID  `json:"buyer_id"`
	LastMessageAt *time.Time `json:"last_message_at"`
	SellerID      uuid.UUID  `json:"seller_id"`
}

// The two participants (buyer, and the listing's seller) plus last_message_at,
// for authz, first-message detection, and read marking on the message routes.
func (q *Queries) GetThreadParticipants(ctx context.Context, id uuid.UUID) (GetThreadParticipantsRow, error) {
	row := q.db.QueryRow(ctx, getThreadParticipants, id)
	var i GetThreadParticipantsRow
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.LastMessageAt,
		&i.SellerID,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (id, thread_id, sender_id, body, image_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, thread_id, sender_id, body, created_at, image_key
`

type InsertMessageParams struct {
	ID       uuid.UUID `json:"id"`
	ThreadID uuid.UUID `json:"thread_id"`
	SenderID uuid.UUID `json:"sender_id"`
	Body     *string   `json:"body"`
	ImageKey *string   `json:"image_key"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ThreadID,
		arg.SenderID,
		arg.Body,
		arg.ImageKey,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
		&i.ImageKey,
	)
	return i, err
}

const listExpiredMessageBatch = `-- name: ListExpiredMessageBatch :many
SELECT m.id, m.image_key
FROM messages m
JOIN chat_threads t ON t.id = m.thread_id
JOIN listings l ON l.id = t.listing_id
JOIN races r ON r.id = l.race_id
WHERE r.event_date < $1
ORDER BY m.id
LIMIT $2
`

type ListExpiredMessageBatchParams struct {
	Cutoff    time.Time `json:"cutoff"`
	BatchSize int32     `json:"batch_size"`
}

type ListExpiredMessageBatchRow struct {
	ID       uuid.UUID `json:"id"`
	ImageKey *string   `json:"image_key"`
}

// One batch (up to batch_size, oldest id first) of messages whose race
// finished before the cutoff (12 months after race event_date) - id and
// image_key, so DeleteExpiredMessagesByID can delete exactly this same set
// and the retention job can remove exactly these objects from storage. Two
// independent LIMITed queries could each pick a different batch and leave a
// harvested key's message un-deleted (or vice versa); going by id fixes that
// (#99).
func (q *Queries) ListExpiredMessageBatch(ctx context.Context, arg ListExpiredMessageBatchParams) ([]ListExpiredMessageBatchRow, error) {
	rows, err := q.db.Query(ctx, listExpiredMessageBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredMessageBatchRow
	for rows.Next() {
		var i ListExpiredMessageBatchRow
		if err := rows.Scan(&i.ID, &i.ImageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, thread_id, sender_id, body, created_at, image_key FROM messages
WHERE thread_id = $1
  AND ($2::uuid IS NULL OR id > $2)
ORDER BY id
LIMIT $3
`

type ListMessagesParams struct {
	ThreadID uuid.UUID  `json:"thread_id"`
	Cursor   *uuid.UUID `json:"cursor"`
	PageSize int32      `json:"page_size"`
}

// Cursor-poll: ascending by id (UUIDv7, time-ordered), only newer than the
// caller's cursor. Covered by messages_thread_idx (thread_id, id).
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ThreadID, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
			&i.ImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForUser = `-- name: ListThreadsForUser :many
SELECT
    t.id, t.listing_id, t.buyer_id, t.last_message_at,
    l.seller_id,
    r.name AS race_name, r.slug AS race_slug,
    bu.display_name AS buyer_name,
    su.display_name AS seller_name,
    (SELECT count(*) FROM messages m
       WHERE m.thread_id = t.id
         AND m.sender_id <> $1
         AND (
           CASE WHEN t.buyer_id = $1 THEN t.buyer_last_read_at ELSE t.seller_last_read_at END IS NULL
           OR m.created_at > CASE WHEN t.buyer_id = $1 THEN t.buyer_last_read_at ELSE t.seller_last_read_at END
         )) AS unread_count
FROM chat_threads t
JOIN listings l ON l.id = t.listing_id
JOIN races r ON r.id = l.race_id
JOIN users bu ON bu.id = t.buyer_id
JOIN users su ON su.id = l.seller_id
WHERE t.buyer_id = $1 OR l.seller_id = $1
ORDER BY t.last_message_at DESC NULLS LAST
`

type ListThreadsForUserRow struct {
	ID            uuid.UUID  `json:"id"`
	ListingID     uuid.UUID  `json:"listing_id"`
	BuyerID       uuid.UUID  `json:"buyer_id"`
	LastMessageAt *time.Time `json:"last_message_at"`
	SellerID      uuid.UUID  `json:"seller_id"`
	RaceName      string     `json:"race_name"`
	RaceSlug      string     `json:"race_slug"`
	BuyerName     string     `json:"buyer_name"`
	SellerName    string     `json:"seller_name"`
	UnreadCount   int64      `json:"unread_count"`
}

// Inbox: every thread where the caller is the buyer or the listing's seller,
// with race context, both party names (the handler picks the "other" one), and
// the caller's unread count. The unread subquery is bounded by a user's thread
// count; revisit with a denormalized counter if an inbox grows large.
func (q *Queries) ListThreadsForUser(ctx context.Context, senderID uuid.UUID) ([]ListThreadsForUserRow, error) {
	rows, err := q.db.Query(ctx, listThreadsForUser, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadsForUserRow
	for rows.Next() {
		var i ListThreadsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.LastMessageAt,
			&i.SellerID,
			&i.RaceName,
			&i.RaceSlug,
			&i.BuyerName,
			&i.SellerName,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markThreadRead = `-- name: MarkThreadRead :exec
UPDATE chat_threads
SET buyer_last_read_at  = CASE WHEN buyer_id  = $1 THEN $2 ELSE buyer_last_read_at  END,
    seller_last_read_at = CASE WHEN buyer_id <> $1 THEN $2 ELSE seller_last_read_at END
WHERE id = $3
`

type MarkThreadReadParams struct {
	Reader uuid.UUID  `json:"reader"`
	ReadAt *time.Time `json:"read_at"`
	ID     uuid.UUID  `json:"id"`
}

// Advances the reader's last_read to the newest message they fetched. The
// handler guarantees the reader is a participant.
func (q *Queries) MarkThreadRead(ctx context.Context, arg MarkThreadReadParams) error {
	_, err := q.db.Exec(ctx, markThreadRead, arg.Reader, arg.ReadAt, arg.ID)
	return err
}

const touchThreadOnMessage = `-- name: TouchThreadOnMessage :exec
UPDATE chat_threads
SET last_message_at = now(),
    buyer_last_read_at  = CASE WHEN buyer_id  = $2 THEN now() ELSE buyer_last_read_at  END,
    seller_last_read_at = CASE WHEN buyer_id <> $2 THEN now() ELSE seller_last_read_at END
WHERE id = $1
`

type TouchThreadOnMessageParams struct {
	ID      uuid.UUID `json:"id"`
	BuyerID uuid.UUID `json:"buyer_id"`
}

// Bumps last_message_at and marks the sender's own side read (you have read what
// you just sent). The handler guarantees the sender is a participant.
func (q *Queries) TouchThreadOnMessage(ctx context.Context, arg TouchThreadOnMessageParams) error {
	_, err := q.db.Exec(ctx, touchThreadOnMessage, arg.ID, arg.BuyerID)
	return err
}
