// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcgen

import (
	"context"
)

const tryAdvisoryXactLock = `-- name: TryAdvisoryXactLock :one

SELECT pg_try_advisory_xact_lock($1::bigint)
`

// Generic background-job coordination. A transaction-scoped advisory lock lets
// every API instance run the same ticker while only one does the work per tick
// (architecture invariant 5: stateless API, jobs coordinate via Postgres
// advisory locks). The lock auto-releases when the transaction ends.
func (q *Queries) TryAdvisoryXactLock(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryXactLock, key)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
