// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createListing = `-- name: CreateListing :one
INSERT INTO listings (
    id, race_id, seller_id, price_cents, currency, original_price_cents,
    description, image_key, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, race_id, seller_id, status, price_cents, currency, original_price_cents, description, image_key, created_at, updated_at, expires_at
`

type CreateListingParams struct {
	ID                 uuid.UUID `json:"id"`
	RaceID             uuid.UUID `json:"race_id"`
	SellerID           uuid.UUID `json:"seller_id"`
	PriceCents         *int32    `json:"price_cents"`
	Currency           string    `json:"currency"`
	OriginalPriceCents *int32    `json:"original_price_cents"`
	Description        *string   `json:"description"`
	ImageKey           *string   `json:"image_key"`
	ExpiresAt          time.Time `json:"expires_at"`
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.ID,
		arg.RaceID,
		arg.SellerID,
		arg.PriceCents,
		arg.Currency,
		arg.OriginalPriceCents,
		arg.Description,
		arg.ImageKey,
		arg.ExpiresAt,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.RaceID,
		&i.SellerID,
		&i.Status,
		&i.PriceCents,
		&i.Currency,
		&i.OriginalPriceCents,
		&i.Description,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const expirePastRaceListings = `-- name: ExpirePastRaceListings :execrows
UPDATE listings l
SET status = 'expired', updated_at = now()
WHERE l.id IN (
    SELECT l2.id FROM listings l2
    JOIN races r ON r.id = l2.race_id
    WHERE l2.status = 'active' AND r.event_date < $1
    LIMIT $2
)
`

type ExpirePastRaceListingsParams struct {
	Cutoff    time.Time `json:"cutoff"`
	BatchSize int32     `json:"batch_size"`
}

// Flips up to batch_size active listings to 'expired' once their race is over
// (event_date is before the cutoff, i.e. start of today UTC). The job calls
// this in a loop, each call its own transaction, so a large backlog doesn't
// pay for one unbounded UPDATE holding every matching row lock at once (#99).
// Returns the number expired in this batch.
func (q *Queries) ExpirePastRaceListings(ctx context.Context, arg ExpirePastRaceListingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expirePastRaceListings, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getListingByID = `-- name: GetListingByID :one
SELECT listings.id, listings.race_id, listings.seller_id, listings.status, listings.price_cents, listings.currency, listings.original_price_cents, listings.description, listings.image_key, listings.created_at, listings.updated_at, listings.expires_at, races.id, races.slug, races.name, races.series, races.sport, races.distance, races.event_date, races.city, races.country, races.website_url, races.transfer_policy, races.official_transfer_url, races.policy_source_url, races.policy_notes, races.policy_verified_at, races.policy_verified_by, races.status, races.created_by, races.created_at, races.updated_at, u.display_name AS seller_name
FROM listings
JOIN races ON races.id = listings.race_id
JOIN users u ON u.id = listings.seller_id
WHERE listings.id = $1
`

type GetListingByIDRow struct {
	Listing    Listing `json:"listing"`
	Race       Race    `json:"race"`
	SellerName string  `json:"seller_name"`
}

func (q *Queries) GetListingByID(ctx context.Context, id uuid.UUID) (GetListingByIDRow, error) {
	row := q.db.QueryRow(ctx, getListingByID, id)
	var i GetListingByIDRow
	err := row.Scan(
		&i.Listing.ID,
		&i.Listing.RaceID,
		&i.Listing.SellerID,
		&i.Listing.Status,
		&i.Listing.PriceCents,
		&i.Listing.Currency,
		&i.Listing.OriginalPriceCents,
		&i.Listing.Description,
		&i.Listing.ImageKey,
		&i.Listing.CreatedAt,
		&i.Listing.UpdatedAt,
		&i.Listing.ExpiresAt,
		&i.Race.ID,
		&i.Race.Slug,
		&i.Race.Name,
		&i.Race.Series,
		&i.Race.Sport,
		&i.Race.Distance,
		&i.Race.EventDate,
		&i.Race.City,
		&i.Race.Country,
		&i.Race.WebsiteUrl,
		&i.Race.TransferPolicy,
		&i.Race.OfficialTransferUrl,
		&i.Race.PolicySourceUrl,
		&i.Race.PolicyNotes,
		&i.Race.PolicyVerifiedAt,
		&i.Race.PolicyVerifiedBy,
		&i.Race.Status,
		&i.Race.CreatedBy,
		&i.Race.CreatedAt,
		&i.Race.UpdatedAt,
		&i.SellerName,
	)
	return i, err
}

const listActiveListingsByRace = `-- name: ListActiveListingsByRace :many
SELECT l.id, l.race_id, l.seller_id, l.status, l.price_cents, l.currency, l.original_price_cents, l.description, l.image_key, l.created_at, l.updated_at, l.expires_at, u.display_name AS seller_name
FROM listings l
JOIN users u ON u.id = l.seller_id
WHERE l.race_id = $1
  AND l.status = 'active'
  AND ($2::uuid IS NULL OR l.id < $2)
ORDER BY l.id DESC
LIMIT $3
`

type ListActiveListingsByRaceParams struct {
	RaceID   uuid.UUID  `json:"race_id"`
	CursorID *uuid.UUID `json:"cursor_id"`
	PageSize int32      `json:"page_size"`
}

type ListActiveListingsByRaceRow struct {
	ID                 uuid.UUID `json:"id"`
	RaceID             uuid.UUID `json:"race_id"`
	SellerID           uuid.UUID `json:"seller_id"`
	Status             string    `json:"status"`
	PriceCents         *int32    `json:"price_cents"`
	Currency           string    `json:"currency"`
	OriginalPriceCents *int32    `json:"original_price_cents"`
	Description        *string   `json:"description"`
	ImageKey           *string   `json:"image_key"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	ExpiresAt          time.Time `json:"expires_at"`
	SellerName         string    `json:"seller_name"`
}

func (q *Queries) ListActiveListingsByRace(ctx context.Context, arg ListActiveListingsByRaceParams) ([]ListActiveListingsByRaceRow, error) {
	rows, err := q.db.Query(ctx, listActiveListingsByRace, arg.RaceID, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveListingsByRaceRow
	for rows.Next() {
		var i ListActiveListingsByRaceRow
		if err := rows.Scan(
			&i.ID,
			&i.RaceID,
			&i.SellerID,
			&i.Status,
			&i.PriceCents,
			&i.Currency,
			&i.OriginalPriceCents,
			&i.Description,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingsBySeller = `-- name: ListListingsBySeller :many
SELECT l.id, l.race_id, l.seller_id, l.status, l.price_cents, l.currency, l.original_price_cents, l.description, l.image_key, l.created_at, l.updated_at, l.expires_at, r.name AS race_name, r.slug AS race_slug, r.event_date
FROM listings l
JOIN races r ON r.id = l.race_id
WHERE l.seller_id = $1
ORDER BY l.created_at DESC
`

type ListListingsBySellerRow struct {
	ID                 uuid.UUID `json:"id"`
	RaceID             uuid.UUID `json:"race_id"`
	SellerID           uuid.UUID `json:"seller_id"`
	Status             string    `json:"status"`
	PriceCents         *int32    `json:"price_cents"`
	Currency           string    `json:"currency"`
	OriginalPriceCents *int32    `json:"original_price_cents"`
	Description        *string   `json:"description"`
	ImageKey           *string   `json:"image_key"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	ExpiresAt          time.Time `json:"expires_at"`
	RaceName           string    `json:"race_name"`
	RaceSlug           string    `json:"race_slug"`
	EventDate          time.Time `json:"event_date"`
}

func (q *Queries) ListListingsBySeller(ctx context.Context, sellerID uuid.UUID) ([]ListListingsBySellerRow, error) {
	rows, err := q.db.Query(ctx, listListingsBySeller, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListingsBySellerRow
	for rows.Next() {
		var i ListListingsBySellerRow
		if err := rows.Scan(
			&i.ID,
			&i.RaceID,
			&i.SellerID,
			&i.Status,
			&i.PriceCents,
			&i.Currency,
			&i.OriginalPriceCents,
			&i.Description,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.RaceName,
			&i.RaceSlug,
			&i.EventDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListing = `-- name: UpdateListing :one
UPDATE listings
SET price_cents = $2, original_price_cents = $3, description = $4, updated_at = now()
WHERE id = $1 AND seller_id = $5 AND status = 'active'
RETURNING id, race_id, seller_id, status, price_cents, currency, original_price_cents, description, image_key, created_at, updated_at, expires_at
`

type UpdateListingParams struct {
	ID                 uuid.UUID `json:"id"`
	PriceCents         *int32    `json:"price_cents"`
	OriginalPriceCents *int32    `json:"original_price_cents"`
	Description        *string   `json:"description"`
	SellerID           uuid.UUID `json:"seller_id"`
}

// Guarded so the edit is atomic with the owner/active checks the handler made:
// if the listing changed owner (never happens today) or left 'active' between
// the read and here, no row matches and the handler maps ErrNoRows to 409.
func (q *Queries) UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, updateListing,
		arg.ID,
		arg.PriceCents,
		arg.OriginalPriceCents,
		arg.Description,
		arg.SellerID,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.RaceID,
		&i.SellerID,
		&i.Status,
		&i.PriceCents,
		&i.Currency,
		&i.OriginalPriceCents,
		&i.Description,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateListingStatus = `-- name: UpdateListingStatus :one
UPDATE listings
SET status = $1, updated_at = now()
WHERE id = $2 AND status = $3
RETURNING id, race_id, seller_id, status, price_cents, currency, original_price_cents, description, image_key, created_at, updated_at, expires_at
`

type UpdateListingStatusParams struct {
	ToStatus   string    `json:"to_status"`
	ID         uuid.UUID `json:"id"`
	FromStatus string    `json:"from_status"`
}

func (q *Queries) UpdateListingStatus(ctx context.Context, arg UpdateListingStatusParams) (Listing, error) {
	row := q.db.QueryRow(ctx, updateListingStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.RaceID,
		&i.SellerID,
		&i.Status,
		&i.PriceCents,
		&i.Currency,
		&i.OriginalPriceCents,
		&i.Description,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
