// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID          int64      `json:"id"`
	AdminID     uuid.UUID  `json:"admin_id"`
	Action      string     `json:"action"`
	SubjectType string     `json:"subject_type"`
	SubjectID   *uuid.UUID `json:"subject_id"`
	Details     []byte     `json:"details"`
	CreatedAt   time.Time  `json:"created_at"`
}

type ChatThread struct {
	ID               uuid.UUID  `json:"id"`
	ListingID        uuid.UUID  `json:"listing_id"`
	BuyerID          uuid.UUID  `json:"buyer_id"`
	CreatedAt        time.Time  `json:"created_at"`
	LastMessageAt    *time.Time `json:"last_message_at"`
	BuyerLastReadAt  *time.Time `json:"buyer_last_read_at"`
	SellerLastReadAt *time.Time `json:"seller_last_read_at"`
}

type EmailVerification struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Listing struct {
	ID                 uuid.UUID `json:"id"`
	RaceID             uuid.UUID `json:"race_id"`
	SellerID           uuid.UUID `json:"seller_id"`
	Status             string    `json:"status"`
	PriceCents         *int32    `json:"price_cents"`
	Currency           string    `json:"currency"`
	OriginalPriceCents *int32    `json:"original_price_cents"`
	Description        *string   `json:"description"`
	ImageKey           *string   `json:"image_key"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	ExpiresAt          time.Time `json:"expires_at"`
}

type Message struct {
	ID        uuid.UUID `json:"id"`
	ThreadID  uuid.UUID `json:"thread_id"`
	SenderID  uuid.UUID `json:"sender_id"`
	Body      *string   `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	ImageKey  *string   `json:"image_key"`
}

type Order struct {
	ID                    uuid.UUID  `json:"id"`
	ListingID             uuid.UUID  `json:"listing_id"`
	BuyerID               uuid.UUID  `json:"buyer_id"`
	SellerID              uuid.UUID  `json:"seller_id"`
	State                 string     `json:"state"`
	ItemAmountCents       int32      `json:"item_amount_cents"`
	ProcessingFeeCents    int32      `json:"processing_fee_cents"`
	TotalAmountCents      int32      `json:"total_amount_cents"`
	Currency              string     `json:"currency"`
	StripePaymentIntentID *string    `json:"stripe_payment_intent_id"`
	StripeTransferID      *string    `json:"stripe_transfer_id"`
	ReservedUntil         *time.Time `json:"reserved_until"`
	SellerMarkedAt        *time.Time `json:"seller_marked_at"`
	CompletedAt           *time.Time `json:"completed_at"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

type OrderEvent struct {
	ID            int64     `json:"id"`
	OrderID       uuid.UUID `json:"order_id"`
	FromState     *string   `json:"from_state"`
	ToState       string    `json:"to_state"`
	Actor         string    `json:"actor"`
	Reason        *string   `json:"reason"`
	StripeEventID *string   `json:"stripe_event_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type PasswordReset struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type PolicyAck struct {
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
	RaceID  uuid.UUID `json:"race_id"`
	Policy  string    `json:"policy"`
	AckedAt time.Time `json:"acked_at"`
}

type Race struct {
	ID                  uuid.UUID  `json:"id"`
	Slug                string     `json:"slug"`
	Name                string     `json:"name"`
	Series              *string    `json:"series"`
	Sport               string     `json:"sport"`
	Distance            *string    `json:"distance"`
	EventDate           time.Time  `json:"event_date"`
	City                string     `json:"city"`
	Country             string     `json:"country"`
	WebsiteUrl          *string    `json:"website_url"`
	TransferPolicy      string     `json:"transfer_policy"`
	OfficialTransferUrl *string    `json:"official_transfer_url"`
	PolicySourceUrl     *string    `json:"policy_source_url"`
	PolicyNotes         *string    `json:"policy_notes"`
	PolicyVerifiedAt    *time.Time `json:"policy_verified_at"`
	PolicyVerifiedBy    *uuid.UUID `json:"policy_verified_by"`
	Status              string     `json:"status"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

type Report struct {
	ID            uuid.UUID  `json:"id"`
	ReporterID    *uuid.UUID `json:"reporter_id"`
	ReporterEmail *string    `json:"reporter_email"`
	SubjectType   string     `json:"subject_type"`
	SubjectID     uuid.UUID  `json:"subject_id"`
	Reason        string     `json:"reason"`
	Details       *string    `json:"details"`
	Status        string     `json:"status"`
	CreatedAt     time.Time  `json:"created_at"`
	ResolvedAt    *time.Time `json:"resolved_at"`
	ResolvedBy    *uuid.UUID `json:"resolved_by"`
}

type Session struct {
	TokenHash  []byte      `json:"token_hash"`
	UserID     uuid.UUID   `json:"user_id"`
	CreatedAt  time.Time   `json:"created_at"`
	LastSeenAt time.Time   `json:"last_seen_at"`
	ExpiresAt  time.Time   `json:"expires_at"`
	Ip         *netip.Addr `json:"ip"`
	UserAgent  *string     `json:"user_agent"`
}

type StripeEvent struct {
	ID          string    `json:"id"`
	Type        string    `json:"type"`
	Payload     []byte    `json:"payload"`
	ProcessedAt time.Time `json:"processed_at"`
}

type User struct {
	ID               uuid.UUID  `json:"id"`
	Email            string     `json:"email"`
	EmailVerifiedAt  *time.Time `json:"email_verified_at"`
	PasswordHash     string     `json:"password_hash"`
	DisplayName      string     `json:"display_name"`
	Locale           string     `json:"locale"`
	Country          *string    `json:"country"`
	Role             string     `json:"role"`
	StripeAccountID  *string    `json:"stripe_account_id"`
	StripeCustomerID *string    `json:"stripe_customer_id"`
	AnonymizedAt     *time.Time `json:"anonymized_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}
