// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createBlock = `-- name: CreateBlock :exec
INSERT INTO blocks (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT (blocker_id, blocked_id) DO NOTHING
`

type CreateBlockParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

// Idempotent: blocking an already-blocked user is a no-op.
func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (id, reporter_id, subject_type, subject_id, reason, details)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, reporter_id, reporter_email, subject_type, subject_id, reason, details, status, created_at, resolved_at, resolved_by
`

type CreateReportParams struct {
	ID          uuid.UUID  `json:"id"`
	ReporterID  *uuid.UUID `json:"reporter_id"`
	SubjectType string     `json:"subject_type"`
	SubjectID   uuid.UUID  `json:"subject_id"`
	Reason      string     `json:"reason"`
	Details     *string    `json:"details"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ReporterID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Reason,
		arg.Details,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReporterEmail,
		&i.SubjectType,
		&i.SubjectID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type DeleteBlockParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS (
    SELECT 1 FROM blocks
    WHERE (blocker_id = $1 AND blocked_id = $2)
       OR (blocker_id = $2 AND blocked_id = $1)
)
`

type IsBlockedParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

// True if either user has blocked the other - a block silences the conversation
// both ways.
func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
