// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordReset = `-- name: CreatePasswordReset :one

INSERT INTO password_resets (token_hash, user_id, expires_at)
VALUES ($1, $2, now() + interval '1 hour')
RETURNING expires_at
`

type CreatePasswordResetParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
}

// Password reset lifecycle. The 1-hour TTL lives here (both the INSERT and the
// not-expired guard), tighter than the 24-hour verification token because a
// reset grants full account access.
func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.TokenHash, arg.UserID)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const deletePasswordResetsForUser = `-- name: DeletePasswordResetsForUser :exec
DELETE FROM password_resets WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetsForUser, userID)
	return err
}

const getPasswordResetUser = `-- name: GetPasswordResetUser :one
SELECT user_id FROM password_resets
WHERE token_hash = $1
  AND expires_at > now()
`

func (q *Queries) GetPasswordResetUser(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPasswordResetUser, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
