// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: race.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRace = `-- name: CreateRace :one
INSERT INTO races (
    id, slug, name, series, sport, distance, event_date, city, country,
    website_url, transfer_policy, official_transfer_url, policy_source_url,
    policy_notes, policy_verified_at, policy_verified_by, status, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, slug, name, series, sport, distance, event_date, city, country, website_url, transfer_policy, official_transfer_url, policy_source_url, policy_notes, policy_verified_at, policy_verified_by, status, created_by, created_at, updated_at
`

type CreateRaceParams struct {
	ID                  uuid.UUID  `json:"id"`
	Slug                string     `json:"slug"`
	Name                string     `json:"name"`
	Series              *string    `json:"series"`
	Sport               string     `json:"sport"`
	Distance            *string    `json:"distance"`
	EventDate           time.Time  `json:"event_date"`
	City                string     `json:"city"`
	Country             string     `json:"country"`
	WebsiteUrl          *string    `json:"website_url"`
	TransferPolicy      string     `json:"transfer_policy"`
	OfficialTransferUrl *string    `json:"official_transfer_url"`
	PolicySourceUrl     *string    `json:"policy_source_url"`
	PolicyNotes         *string    `json:"policy_notes"`
	PolicyVerifiedAt    *time.Time `json:"policy_verified_at"`
	PolicyVerifiedBy    *uuid.UUID `json:"policy_verified_by"`
	Status              string     `json:"status"`
	CreatedBy           *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateRace(ctx context.Context, arg CreateRaceParams) (Race, error) {
	row := q.db.QueryRow(ctx, createRace,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Series,
		arg.Sport,
		arg.Distance,
		arg.EventDate,
		arg.City,
		arg.Country,
		arg.WebsiteUrl,
		arg.TransferPolicy,
		arg.OfficialTransferUrl,
		arg.PolicySourceUrl,
		arg.PolicyNotes,
		arg.PolicyVerifiedAt,
		arg.PolicyVerifiedBy,
		arg.Status,
		arg.CreatedBy,
	)
	var i Race
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Series,
		&i.Sport,
		&i.Distance,
		&i.EventDate,
		&i.City,
		&i.Country,
		&i.WebsiteUrl,
		&i.TransferPolicy,
		&i.OfficialTransferUrl,
		&i.PolicySourceUrl,
		&i.PolicyNotes,
		&i.PolicyVerifiedAt,
		&i.PolicyVerifiedBy,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRaceBySlug = `-- name: GetRaceBySlug :one
SELECT r.id, r.slug, r.name, r.series, r.sport, r.distance, r.event_date, r.city, r.country, r.website_url, r.transfer_policy, r.official_transfer_url, r.policy_source_url, r.policy_notes, r.policy_verified_at, r.policy_verified_by, r.status, r.created_by, r.created_at, r.updated_at,
    (SELECT count(*) FROM listings l
      WHERE l.race_id = r.id AND l.status = 'active') AS active_listings
FROM races r
WHERE r.slug = $1
`

type GetRaceBySlugRow struct {
	ID                  uuid.UUID  `json:"id"`
	Slug                string     `json:"slug"`
	Name                string     `json:"name"`
	Series              *string    `json:"series"`
	Sport               string     `json:"sport"`
	Distance            *string    `json:"distance"`
	EventDate           time.Time  `json:"event_date"`
	City                string     `json:"city"`
	Country             string     `json:"country"`
	WebsiteUrl          *string    `json:"website_url"`
	TransferPolicy      string     `json:"transfer_policy"`
	OfficialTransferUrl *string    `json:"official_transfer_url"`
	PolicySourceUrl     *string    `json:"policy_source_url"`
	PolicyNotes         *string    `json:"policy_notes"`
	PolicyVerifiedAt    *time.Time `json:"policy_verified_at"`
	PolicyVerifiedBy    *uuid.UUID `json:"policy_verified_by"`
	Status              string     `json:"status"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	ActiveListings      int64      `json:"active_listings"`
}

func (q *Queries) GetRaceBySlug(ctx context.Context, slug string) (GetRaceBySlugRow, error) {
	row := q.db.QueryRow(ctx, getRaceBySlug, slug)
	var i GetRaceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Series,
		&i.Sport,
		&i.Distance,
		&i.EventDate,
		&i.City,
		&i.Country,
		&i.WebsiteUrl,
		&i.TransferPolicy,
		&i.OfficialTransferUrl,
		&i.PolicySourceUrl,
		&i.PolicyNotes,
		&i.PolicyVerifiedAt,
		&i.PolicyVerifiedBy,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveListings,
	)
	return i, err
}

const listRaces = `-- name: ListRaces :many
SELECT r.id, r.slug, r.name, r.series, r.sport, r.distance, r.event_date, r.city, r.country, r.website_url, r.transfer_policy, r.official_transfer_url, r.policy_source_url, r.policy_notes, r.policy_verified_at, r.policy_verified_by, r.status, r.created_by, r.created_at, r.updated_at,
    (SELECT count(*) FROM listings l
      WHERE l.race_id = r.id AND l.status = 'active') AS active_listings
FROM races r
WHERE r.status = 'published'
  AND ($1::text IS NULL OR r.country = $1)
  AND ($2::text IS NULL OR r.sport = $2)
  AND ($3::text IS NULL OR r.transfer_policy = $3)
  AND ($4::date IS NULL OR r.event_date >= $4)
  AND ($5::date IS NULL OR r.event_date <= $5)
  AND ($6::text IS NULL
       OR to_tsvector('simple', r.name || ' ' || r.city)
          @@ plainto_tsquery('simple', $6))
  AND ($7::date IS NULL
       OR (r.event_date, r.id) > ($7, $8::uuid))
ORDER BY r.event_date, r.id
LIMIT $9
`

type ListRacesParams struct {
	Country        *string    `json:"country"`
	Sport          *string    `json:"sport"`
	TransferPolicy *string    `json:"transfer_policy"`
	DateFrom       *time.Time `json:"date_from"`
	DateTo         *time.Time `json:"date_to"`
	Search         *string    `json:"search"`
	CursorDate     *time.Time `json:"cursor_date"`
	CursorID       *uuid.UUID `json:"cursor_id"`
	PageSize       int32      `json:"page_size"`
}

type ListRacesRow struct {
	ID                  uuid.UUID  `json:"id"`
	Slug                string     `json:"slug"`
	Name                string     `json:"name"`
	Series              *string    `json:"series"`
	Sport               string     `json:"sport"`
	Distance            *string    `json:"distance"`
	EventDate           time.Time  `json:"event_date"`
	City                string     `json:"city"`
	Country             string     `json:"country"`
	WebsiteUrl          *string    `json:"website_url"`
	TransferPolicy      string     `json:"transfer_policy"`
	OfficialTransferUrl *string    `json:"official_transfer_url"`
	PolicySourceUrl     *string    `json:"policy_source_url"`
	PolicyNotes         *string    `json:"policy_notes"`
	PolicyVerifiedAt    *time.Time `json:"policy_verified_at"`
	PolicyVerifiedBy    *uuid.UUID `json:"policy_verified_by"`
	Status              string     `json:"status"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	ActiveListings      int64      `json:"active_listings"`
}

func (q *Queries) ListRaces(ctx context.Context, arg ListRacesParams) ([]ListRacesRow, error) {
	rows, err := q.db.Query(ctx, listRaces,
		arg.Country,
		arg.Sport,
		arg.TransferPolicy,
		arg.DateFrom,
		arg.DateTo,
		arg.Search,
		arg.CursorDate,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRacesRow
	for rows.Next() {
		var i ListRacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Series,
			&i.Sport,
			&i.Distance,
			&i.EventDate,
			&i.City,
			&i.Country,
			&i.WebsiteUrl,
			&i.TransferPolicy,
			&i.OfficialTransferUrl,
			&i.PolicySourceUrl,
			&i.PolicyNotes,
			&i.PolicyVerifiedAt,
			&i.PolicyVerifiedBy,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveListings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
