// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, display_name, locale, country)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, email_verified_at, password_hash, display_name, locale, country, role, stripe_account_id, stripe_customer_id, anonymized_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	Locale       string    `json:"locale"`
	Country      *string   `json:"country"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Locale,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.Country,
		&i.Role,
		&i.StripeAccountID,
		&i.StripeCustomerID,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, password_hash, display_name, locale, country, role, stripe_account_id, stripe_customer_id, anonymized_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.Country,
		&i.Role,
		&i.StripeAccountID,
		&i.StripeCustomerID,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, password_hash, display_name, locale, country, role, stripe_account_id, stripe_customer_id, anonymized_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.Country,
		&i.Role,
		&i.StripeAccountID,
		&i.StripeCustomerID,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
