// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailVerification = `-- name: CreateEmailVerification :one

INSERT INTO email_verifications (token_hash, user_id, expires_at)
VALUES ($1, $2, now() + interval '24 hours')
RETURNING expires_at
`

type CreateEmailVerificationParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
}

// Email verification lifecycle. The 24-hour TTL lives here (both the INSERT and
// the not-expired guard), mirroring the session TTL convention in auth.sql.
func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createEmailVerification, arg.TokenHash, arg.UserID)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const deleteEmailVerificationsForUser = `-- name: DeleteEmailVerificationsForUser :exec
DELETE FROM email_verifications WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationsForUser, userID)
	return err
}

const deleteExpiredEmailVerificationsBatch = `-- name: DeleteExpiredEmailVerificationsBatch :execrows
DELETE FROM email_verifications
WHERE token_hash IN (
    SELECT v.token_hash FROM email_verifications v
    WHERE v.expires_at < $1
    LIMIT $2
)
`

type DeleteExpiredEmailVerificationsBatchParams struct {
	Cutoff    time.Time `json:"cutoff"`
	BatchSize int32     `json:"batch_size"`
}

// Janitor batch (#142): tokens for users who never verify are otherwise only
// removed by account deletion (CASCADE), so expired rows accumulate. Same
// retention buffer as sessions (expiry + 30 days); batch by primary key (#99).
func (q *Queries) DeleteExpiredEmailVerificationsBatch(ctx context.Context, arg DeleteExpiredEmailVerificationsBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailVerificationsBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailVerificationUser = `-- name: GetEmailVerificationUser :one
SELECT user_id FROM email_verifications
WHERE token_hash = $1
  AND expires_at > now()
`

func (q *Queries) GetEmailVerificationUser(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationUser, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified_at = now(), updated_at = now()
WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}
